
using SkyCars.Core.DomainEntity.User;
using SkyCars.Data.Migrations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkyCars.Data.Migration
{
    [MigrationInfo("2022-08-31 15:58:12", "Added User1")]
    public class BaseInitMigration : FluentMigrator.Migration
    {
        public override void Up()
        {
            #region :: User Schema ::
            Create
                .Table(nameof(User1)).WithDescription("User master") //can also pass custom name e.g. .Table("ProductMst")
                .WithColumn(nameof(User1.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(User1.Name)).AsAnsiString(100).NotNullable().WithColumnDescription("name")
                .WithColumn(nameof(User1.Email)).AsAnsiString(100).NotNullable().WithColumnDescription("Email")
                .WithColumn(nameof(User1.Phone)).AsAnsiString(100).NotNullable().WithColumnDescription("Phone")
                .WithColumn(nameof(User1.ProfilePhoto)).AsAnsiString(100).NotNullable().WithColumnDescription("ProfilePhoto")
                .WithColumn(nameof(User1.Gender)).AsAnsiString(100).NotNullable().WithColumnDescription(" Gender")
                .WithColumn(nameof(User1.CityId)).AsAnsiString(100).NotNullable().WithColumnDescription("CityId")
                .WithColumn(nameof(User1.CarId)).AsAnsiString(100).NotNullable().WithColumnDescription("CarId")
                .WithColumn(nameof(User1.IsActive)).AsAnsiString(100).NotNullable().WithColumnDescription("IsActive")
                .WithColumn(nameof(User1.RoleId)).AsAnsiString(100).NotNullable().WithColumnDescription("RoleId")
                .WithColumn(nameof(User1.GoogleId)).AsAnsiString(100).NotNullable().WithColumnDescription("GoogleId")
                .WithColumn(nameof(User1.FacebookId)).AsAnsiString(100).NotNullable().WithColumnDescription("FacebookId")
                .WithColumn(nameof(User1.Channel)).AsAnsiString(100).NotNullable().WithColumnDescription("Channel")
                .WithColumn(nameof(User1.CreatedDate)).AsDateTime().NotNullable().WithColumnDescription("Entry Date")
                .WithColumn(nameof(User1.UpdatedDate)).AsDateTime().Nullable().WithColumnDescription("Entry Update Date")
                .WithColumn(nameof(User1.IsDelete)).AsBoolean().Nullable().WithColumnDescription("For delete").WithDefaultValue(true);
            #endregion

            //Execute.Script("DbScriptMigration/UserDefaultRecored.sql");
            //Execute.Script("DbScriptMigration/logdbschema.sql");
        }

        public override void Down()
        {

        }
    }
}
