
using SkyCars.Core.DomainEntity.BookingTracking;
using SkyCars.Data.Migrations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkyCars.Data.Migration
{
    [MigrationInfo("2022-09-01 17:58:12", "Added new Tracking")]
    public class BookingTrackingMigration : FluentMigrator.Migration
    {
        public override void Up()
        {
            #region :: Tracking Schema ::
            Create
                .Table(nameof(Tracking)).WithDescription("User master") //can also pass custom name e.g. .Table("ProductMst")
                .WithColumn(nameof(Tracking.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(Tracking.LocationName)).AsAnsiString(100).NotNullable().WithColumnDescription("LocationName")
                
                .WithColumn(nameof(Tracking.IsDelete)).AsBoolean().Nullable().WithColumnDescription("For delete").WithDefaultValue(true);
            #endregion

            //Execute.Script("DbScriptMigration/UserDefaultRecored.sql");
            //Execute.Script("DbScriptMigration/logdbschema.sql");
        }

        public override void Down()
        {

        }
    }
}
