using SkyCars.Core.DomainEntity.BookingRefund;
using SkyCars.Data.Migrations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkyCars.Data.Migration
{
    [MigrationInfo("2022-09-02 17:58:12", "Added new Refund")]
    public class REFUNDMigration : FluentMigrator.Migration
    {
        public override void Down()
        {
            //throw new NotImplementedException();
        }

        public override void Up()
        {
            #region :: Refund Schema ::
            Create
                .Table(nameof(Refund)).WithDescription("User master") //can also pass custom name e.g. .Table("ProductMst")
                .WithColumn(nameof(Refund.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                //.WithColumn(nameof(Refund.BookingID)).AsInt32().NotNullable().WithColumnDescription("BookingID")
                //.WithColumn(nameof(Refund.TransactionId)).AsAnsiString(100).NotNullable().WithColumnDescription("TransactionId")
                .WithColumn(nameof(Refund.ChargesPaid)).AsCurrency().NotNullable().WithColumnDescription("ChargesPaid")
                .WithColumn(nameof(Refund.RefundAmount)).AsCurrency().NotNullable().WithColumnDescription("RefundAmount")
                .WithColumn(nameof(Refund.RefundStatus)).AsBoolean().Nullable().WithColumnDescription(" RefundStatus")
                .WithColumn(nameof(Refund.IsDelete)).AsBoolean().Nullable().WithColumnDescription("For delete").WithDefaultValue(true);
            #endregion


        }
    }
}